#! /usr/bin/env sh

# File to test
EXP_SCRIPT="caesar"

# Text colors
COLOR_REST="$(tput sgr0)"
COLOR_RED="$(tput setaf 1)"
COLOR_GREEN="$(tput setaf 2)"

# Test counters
NB_TEST_OK=0
NB_TEST_TOTAL=0

##################################################
# check command line params
##################################################
GIVEN_SCRIPT=""
if [ $# -eq 1 ]
then
    GIVEN_SCRIPT="${1}"
else
    printf "Give the script name in command line\n"
    exit
fi

##################################################
# Check if python is available
##################################################
pyapp=`which python`
if [ "${pyapp:0:1}" == "/" ]
then
    python --version
else
    printf "Python not found\n"
    exit
fi

##################################################
# Check if the script has been given
##################################################
if [ "${GIVEN_SCRIPT}" != "${EXP_SCRIPT}" ]
then
    printf "Give the script name in command line\n"
    exit
fi

##################################################
# Check if the given script exists
##################################################
if [ ! -f "${EXP_SCRIPT}" ]
then
    printf "File not found: ${EXP_SCRIPT}\n"
    exit
fi

##################################################
# Test function
##################################################
run_test () {
    TEST_NAME=$1
    TEST_NUM=$2
    TEST_ARG=$3
    TEST_IN=.test/${TEST_NUM}.in
    TEST_EXP=.test/${TEST_NUM}.exp
    TEST_OUT=".test/${TEST_NUM}_test.out"
    TEST_DIFF=".test/${TEST_NUM}_test.diff"
    ./${EXP_SCRIPT} ${TEST_ARG} < ${TEST_IN}  > ${TEST_OUT}
    diff ${TEST_EXP} ${TEST_OUT} > ${TEST_DIFF}
    NB_DIFF=`cat ${TEST_DIFF} | wc -l`
    NB_TEST_TOTAL=$((NB_TEST_TOTAL+1))
    if [ ${NB_DIFF} -eq 0 ]
    then
        printf "${TEST_NUM} ${COLOR_GREEN}\xE2\x9C\x94${COLOR_REST} ${TEST_NAME}\n"
        rm ${TEST_OUT}
        rm ${TEST_DIFF}
        NB_TEST_OK=$((NB_TEST_OK+1))
    else
        printf "\n"
        printf "${TEST_NUM} ${COLOR_RED}\xE2\x9C\x97${COLOR_REST} ${TEST_NAME}\n"
        printf "./${EXP_SCRIPT} ${TEST_ARG} < ${TEST_IN}  > ${TEST_OUT}\n"
        printf "${COLOR_GREEN}Expected${COLOR_REST}\n"
        grep "<" ${TEST_DIFF}
        printf "${COLOR_RED}Given${COLOR_REST}\n"
        grep ">" ${TEST_DIFF}
        printf "\n"
    fi
}

##################################################
# Run tests
##################################################
run_test "Caesar No param" "01" ""
run_test "Caesar 13: Hi there! -> Uv gurer!" "02" "13"
run_test "Caesar  1: AA -> BB" "03" "1"
run_test "Caesar  1: Ab -> Bc" "04" "1"
run_test "Caesar  2: Ab, cD -> Cd, eF" "05" "2"
run_test "Caesar  5: ExPiaLiDoCiouS" "06" "5"
run_test "Caesar 17: SuperCaliFragiLisTic" "07" "17"
run_test "Caesar 21: JcUnfQnItHntzX" "08" "21"
run_test "Caesar Hello" "09" "HELLO"
run_test "Caesar 1 2 3" "10" "1 2 3"
run_test "Caesar 13 -r: Uv gurer! -> Hi there!" "11" "13 -r"
run_test "Caesar 19 -r: Ab maxkx! -> Hi there!" "12" "19 -r"

##################################################
# Print Summary
##################################################
if [ ${NB_TEST_OK} -eq ${NB_TEST_TOTAL} ]
then
    printf "Validated: ${COLOR_GREEN}${NB_TEST_OK}/${NB_TEST_TOTAL}${COLOR_REST}\n"
else
    printf "Validated: ${COLOR_RED}${NB_TEST_OK}/${NB_TEST_TOTAL}${COLOR_REST}\n"
fi
